name: CD
on:
  push:
    branches: [main]

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Build HTML Assets
        run: uv run --extra docs myst build --html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
      - uses: actions/deploy-pages@v4
  publish:
    environment: pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Build package
        run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
