name: CI

on: push

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - name: Setup testing Python environment
        run: uv sync --extra test
      - name: Run tests
        run: uvx pytest
